### ISSUE TITLE
why obfuscated

### ISSUE THREAD

**Issue by thisman26** [jokeri2222/KaHack#2]

**Comment by jokeri2222** [comment]
Why this is an issue?

**Comment by thisman26** [comment]
> Why this is an issue?

its a security issue im not gonna paste something into my console if i can't read the code you dont even have an open source version.

**Comment by jokeri2222** [comment]
Wrll if you are so interested in this code just use the deobfuscator site. It deobfuscates it perfectly but the variable names are a bit fucked.
