### ISSUE TITLE
Kahack not Working

### ISSUE THREAD

**Issue by CodeCrusader3** [jokeri2222/KaHack#3]
When I put in the game id it goes through but the answers don't show up as the right ones, the auto answer doesn't answer the question right and it doesn't answer the correct amount of points it is set to.

**Comment by jokeri2222** [comment]
> When I put in the game id it goes through but the answers don't show up as the right ones, the auto answer doesn't answer the question right and it doesn't answer the correct amount of points it is set to.

I think your teacher had shuffle answers on
