### ISSUE TITLE
Doesnt work anymore.

### ISSUE THREAD

**Issue by ZZ1CX** [jokeri2222/KaHack#4]
Dont bother wasting your time, kahoot (web) hacks are probably gonna be broken forever 
`
1 . your code hooker doesnt even work, public or not it still pops up as red
2. highlights.. i don't even know as theres no way to tell which one is highlighted IF it even works (which it probably doesn't)
3.  Also auto answer doesn't func. 

The screenshot below shows me playing with this cheat, confused and unsure of what do. I followed the intrtuctions exactly and even triple checked yet was very disappointed.

I would love to see this fixed as I could finally brag and shit on my classmates

Best of luck to you. - ZZ1XC

![Untitled Project](https://github.com/user-attachments/assets/773b6aa6-5c72-449e-8eee-850cc321c49c)

**Comment by jokeri2222** [comment]
Yea the code is propably not working anynore and the question parser deprecated I could try to fix it tho :)

**Comment by jokeri2222** [comment]
It works for me?
![image](https://github.com/user-attachments/assets/0c556367-8046-428d-8f2c-2c2734281e53)
Only once it did answer incorrectly.

**Comment by jokeri2222** [comment]
I tried again and it worked perfectly

**Comment by jokeri2222** [comment]
I am closing this issue now since it works :)
