### ISSUE TITLE
Forbidden access

### ISSUE THREAD

**Issue by RenaudBrevin** [jokeri2222/KaHack#8]
Thanks for your work ! Today i try it but when i put the key, the console respond a error 403 forbidden access. When the key isn't good the respond is 404 not found. So i'm sure that my key is a good but not allow to get informations

**Comment by jokeri2222** [comment]
Hi, what kahoot was this. Can I get a screenshot of the console and the kahack window, please?

**Comment by jokeri2222** [comment]
Seems that this issue was caused by entering a private quiz-id.
